---
- name: "00 bootstrap"
  ansible.builtin.include_tasks: "00_bootstrap.yml"

- name: "01 beat modules"
  ansible.builtin.include_tasks: "01_beat-modules.yml"

- name: "02 docker"
  ansible.builtin.include_tasks: "02_docker.yml"

- name: "03 systemd"
  ansible.builtin.include_tasks: "03_systemd.yml"

- name: "04 beat setup"
  ansible.builtin.include_tasks: "04_beat-setup.yml"
  when: run_beat_setup | default(false)
